### ISSUE TITLE
demo or example

### ISSUE THREAD

**Issue by loovi7** [GeeeG/CloudAAE#1]
Your work is nice and how should i do if i want to measure any object such as an apple?  i mean could you give an example or a demo.  Thanks!!!

**Comment by GeeeG** [comment]
Thank you for the interest. Do you have any particular dataset in mind or just an arbitrary apple? Do you have a 3D model for it?

**Comment by loovi7** [comment]
Wow！ I'm so happy to receive your replication. I'm Studying on measuring the pose of  Arresters like this. How should I do with help of your method CloudAAE?
![E8AE26D4-58DF-46e3-ACC6-DF719D8E055E](https://user-images.githubusercontent.com/42432519/112419262-1006e500-8d66-11eb-8820-f21007c40946.png)

**Comment by loovi7** [comment]
> Wow！ I'm so happy to receive your replication. I'm Studying on measuring the pose of Arresters like this. How should I do with help of your method CloudAAE?
> ![E8AE26D4-58DF-46e3-ACC6-DF719D8E055E](https://user-images.githubusercontent.com/42432519/112419262-1006e500-8d66-11eb-8820-f21007c40946.png)

If I have its 3D model for it ?

**Comment by GeeeG** [comment]
This looks like a really interesting real-world application. Theoritically, if you have the 3D model, and if you have a certain setup, e.g. a camera looking at it on the table. Can measure the rough working range as the 3D translation, and accompany with random 3D rotations, you are able to create synthetic training data for this object following the pipeline, and use the synthetic data to train a cloudAAE for your application.

Practically, by looking at the object I'm a bit worried that its metallic appearance will result in very poor-quality point cloud data during testing time, and there is a very high chance the trained network will not work. But I might be wrong, so the first reality check for you would be capture some point cloud data of this object with a Kinect camera, and see whether the point cloud quality is reasonable for further steps.
