### ISSUE TITLE
How to generate synthetic training data

### ISSUE THREAD

**Issue by JianxiangFENG** [GeeeG/CloudAAE#2]
Hi Ge, 

thanks for sharing this great work! I would like to test it with my own objects. 
But I couldn't find the codes for generating the training data. For ycb dataset, you have already saved them in tf_records datatype in `ycb_video_data_tfRecords/train_syn/`. Could you share more details about this part? 

Best,
Jianxiang

**Comment by GeeeG** [comment]
Hi Jianxiang, I have an example that create similar dataset in: https://github.com/GeeeG/CloudPose/tree/master/ycb_video_data_tfRecords

The difference here is that, instead of writing everything into the tfrecords, you only write the rotation, translation and class_id.
I will try to put an example script for this repo as well but I can't promise on the time. Sorry about that, hope this is somewhat helpful!

**Comment by zhijxzho** [comment]
Hello and thanks for your great work.
I cloned your repo and now I'd like to run the evaluate_cloudAAE_ycbv.py. However, I'm getting the following error.

I'm using python 3.7, with Cuda 11.1.
" " "
Traceback (most recent call last):
  File "evaluate_cloudAAE_ycbv.py", line 26, in <module>
    from tf_sampling import farthest_point_sample, gather_point
  File "/home/dev/Documents/Vyoo/CloudAAE_old/tf_ops/sampling/tf_sampling.py", line 12, in <module>
    sampling_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_sampling_so.so'))
  File "/home/dev/anaconda3/envs/dgcnn/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/dev/Documents/Vyoo/CloudAAE_old/tf_ops/sampling/tf_sampling_so.so: cannot open shared object file: No such file or directory
" " "
Could you please clarify if you know what is the problem and your Python version (2 or 3), Cuda, Tensorflow, and open3D (from source or not)? Also, if you have a dockerfile for the implementation, please share it.

Many thanks.

**Comment by JianxiangFENG** [comment]
@zhijxzho have you run the bash files in the corresponding folders to compile the libraries?

**Comment by GeeeG** [comment]
@JianxiangFENG thanks for the clarification!
@zhijxzho it looks like you are missing the "tf_sampling_so.so" file which you should be able to generate by running the .sh script under the same directory. You need to change the paths accordingly. 
I was using Python 2.7 Tensorflow 1.12 cuda 11.3, the open3d is only for visualization (I don't recall the version at the moment), and I install it with pip. 
There's no docker for this implementation, but you should be able to get it runing after compiling.
