### ISSUE TITLE
Can this project run on RTX3090?

### ISSUE THREAD

**Issue by Xenos24R** [GeeeG/CloudAAE#3]
Dear GeeeG：
    First of all, thank you for your contribution to this project, which has brought great inspiration to my research work.
    Recently I tried to run this project on RTX3090, but often encountered unexpected errors, I learned that 30-series graphics cards do not support the CUDA11.x version below, I found in another issue you are using CUDA11.3 to run this project, I would like to ask you how to do it.
    Thank you again for your contribution to this project.

**Comment by GeeeG** [comment]
Hi @Xenos24R , thanks for the interest in this work. What kind of error do you encounter? This project was tested on NVIDIA TITAN X and 1080, so I'm not sure why it would not run on a newer GPU if the drivers are set up properly. Have you tested other projects on your GPU?

**Comment by Xenos24R** [comment]
Thank you for your reply, I've got some bugs about graphics memory overflow, I think this is due to the 30-series graphics card updated the architecture,I encountered the same error while running other projects.
Once again, I salute your work.
