### ISSUE TITLE
Hoe to get experiment results on LM and LMO datatset?

### ISSUE THREAD

**Issue by ZJU-PLP** [GeeeG/CloudAAE#5]
Dear Ge:
      Thanks for sharing so nice work and releasing your code.  
      However, I cannot find the train and test code to get experiment results on **LM and LMO datatset**. Would you mind giving some guidelines to reproduce experiment results in terms of these dataset?

**Comment by GeeeG** [comment]
Hi, thank you for your interest in our work! Basically the train/test code for LM(O) is more or less the same with the ones for YCB video dataset, the only main difference is the train&test data. I have added some scripts for this, you can find them in the linemod_data folder, if this is still relevant for you.
