### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by ChaeChae0505** [GeeeG/CloudAAE#6]
Hello 
you using tensorflow-gpu 1.12.0  (is depend on python 3.5 ~ 3.7 version)
but your code is python 2 
please describe your requirement,,,file

**Comment by GeeeG** [comment]
hi, from my experience tf1.12 also works with python2.7. The code also runs in python 3 if you change the print syntex. 

But for some reason it runs much slower in python3 than in python2, seems some functions are implemented differently in those python versions.

**Comment by ChaeChae0505** [comment]
thank you!
