### ISSUE TITLE
linemod dataset

### ISSUE THREAD

**Issue by tonglily** [GeeeG/CloudAAE#7]
hi,when i run linemod_to_tfrecord_small.py,i encounter a problem--tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but expects int64
it seems to the tensorflow function:tf.py_func,rasie such wrong.
i think it is probably the following tf.int64 rasie the wrong.
x['frame_id'] = tf.py_func(read_frame_id, [x['rgb']], tf.int64)
i have no idea to fix it,hope your reply.

**Comment by GeeeG** [comment]
is your "frame_id" read in int32 format? try to change tf.int64 to tf.int32 to see whether it works

**Comment by tonglily** [comment]
it works,thank you!
